version: '3.7'

# Volumes
#================================================
volumes:
    r-mysql-db:

services:

  r-node:
    image: breitsmiley/upw-rest-preprod:0.0.2
    environment:
      - APP_D_ENTRYPOINT_MODE=init
    ports:
      - "80:3000"
    logging:
        options:
            max-size: "10m"
            max-file: "5"

  r-db:
      image: mysql:8.0.16
      environment:
          - MYSQL_DATABASE=rest
          - MYSQL_USER=rest
          - MYSQL_PASSWORD=rest
          - MYSQL_ROOT_PASSWORD=rest-root
      volumes:
          - type: volume
            source: r-mysql-db
            target: /var/lib/mysql
          - type: bind
            source: ./docker/r-db/mysql-config-file.cnf
            target: /etc/mysql/conf.d/config-file.cnf
      logging:
          options:
              max-size: "10m"
              max-file: "5"
